### ISSUE TITLE
How do I run piston in Ubuntu?

### ISSUE THREAD

**Issue by TransparentMan** [xeroc/piston#12]
So I've downloaded pip and installed piston on my Ubuntu VM.
The Piston python file is in the .local/bin directory.

What commands do I have to enter to run piston?

**Comment by xeroc** [comment]
`~/.local/bin/piston --help`

if you don't want to use the path, you need to add `~/.local/bin` to your `PATH` environmental variable .. there's docs in the ubuntu wiki on how to do that .. I guess

**Comment by gregariomansa** [comment]
~/.local/bin/piston --help

Hi xeroc. Tks for the tip.

I ran this command and the message i get is
bash: /home/julio/.local/bin/piston: No such file or directory

According to
https://steemit.com/piston/@xeroc/piston ,
piston should have been installed in this location when I ran
pip3 install --user steem-piston

Any suggestions?

PS Sorry for being such a noob :-)

**Comment by xeroc** [comment]
Oh, you are installing an outdated package, please install 
pip3 install piston-cli

Also note that currently, piston-lib and piston-cli are unmaintained. The upcoming API changes to steemd may break compatiblity :-/
