### ISSUE TITLE
Better handling of KeyboardInterrupt

### ISSUE THREAD

**Issue by scrawl** [xeroc/piston#15]
Applies to both piston and python-steem. When interrupting the program via Ctrl+C, a crash occurs:
<pre>
Traceback (most recent call last):
  File "time_data.py", line 19, in <module>
    for c in rpc.stream("comment", start=start_block):
  File "/usr/local/lib/python3.4/dist-packages/steemapi/steemnoderpc.py", line 143, in stream
    for block in self.block_stream(*args, **kwargs):
  File "/usr/local/lib/python3.4/dist-packages/steemapi/steemnoderpc.py", line 118, in block_stream
    yield self.get_block(blocknum)
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 373, in method
    r = self.rpcexec(query)
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 330, in rpcexec
    log.debug(json.dumps(ret))
UnboundLocalError: local variable 'ret' referenced before assignment
</pre>

This may be a problem for programs that want to gracefully handle ```KeyboardInterrupt```'s (cleaning up stuff before quitting, etc).

Can be reproduced in the stream_comments example.

**Comment by scrawl** [comment]
When connection is lost, Ctrl+C doesn't even quit the program.

<pre>
^CLost connection to node: ws://localhost:8090 (94/-1) Retrying in 3 seconds
^CLost connection to node: ws://localhost:8090 (95/-1) Retrying in 3 seconds
^CLost connection to node: ws://localhost:8090 (96/-1) Retrying in 3 seconds
^CLost connection to node: ws://localhost:8090 (97/-1) Retrying in 3 seconds
^CLost connection to node: ws://localhost:8090 (98/-1) Retrying in 3 seconds
</pre>

Most likely a catch-all statement that is incorrectly catching KeyboardInterrupts?

**Comment by xeroc** [comment]
I fixed the above error in `develop` of python-graphene.
As for the second issue,  do have an
```
                except KeyboardInterrupt:
                    break
```
in that loop. Not sure what it doesn't behave as expected ...

**Comment by xeroc** [comment]
This problem should be fixed in latest `develop` branch. Thanks for reporting

**Comment by scrawl** [comment]
>  As for the second issue, do have an
> 
>                except KeyboardInterrupt:
>                    break
>in that loop. Not sure what it doesn't behave as expected ...

Shouldn't that be

<pre>
except KeyboardInterrupt:
   raise
</pre>
Instead?

**Comment by scrawl** [comment]
I see you've changed it to this:
<pre>
             except KeyboardInterrupt:
 +                print("Cought key interrupt!")
 +                sys.exit(1)
</pre>

I think that
<pre>
except KeyboardINterrupt:
    raise
</pre>
Would be better, as that allows client applications to catch the KeyboardInterrupt and do what they want with it (gracefully exit, for example).

**Comment by xeroc** [comment]
agreed and fixed
