### ISSUE TITLE
No user feedback immediately after clicking upvote button.

### ISSUE THREAD

**Issue by arhag** [xeroc/piston#18]
I clicked the thumbs up button and I wasn't sure if anything happened until I checked steemd.com to verify the vote transaction did in fact go through. It required a refresh of the page to see the thumbs up icon with the green background (indicating I voted for the post).

**Comment by xeroc** [comment]
it should have given you a notification about one of these three cases

* wallet locked
* voted successful
* vote unsuccessful

voting happens via socket.io connection, maybe there is something wrong about that connections. I should make a check if the connection opens correctly and warn the user if it does not .. 
can you check you JS console for socket.io issues?

**Comment by arhag** [comment]
I guess I didn't notice the notification the first time.

Nevertheless, despite getting the voting notification, the thumbs up icon does not change immediately (it requires refresh) to reflect the upvote. What's worse, I just voted for a comment in the discussion, and it doesn't reflect the vote in the icon even after refresh. In fact, it appears comments do not properly handle votes at all (all vote counts are 0). Is that just a feature that has not yet been implemented?

**Comment by xeroc** [comment]
> Nevertheless, despite getting the voting notification, the thumbs up icon does
> not change immediately (it requires refresh) to reflect the upvote. What's
> worse, I just voted for a comment in the discussion, and it doesn't reflect
> the vote in the icon even after refresh. In fact, it appears comments do not
> properly handle votes at all (all vote counts are 0). Is that just a feature
> that has not yet been implemented?

* clicking the vote button does indeed not yet change it's shape (on the todolist)
* after a successful vote, it should change after refresh.

If am reading the `active_votes` attribute for this. I never understood why it
is called **active** though. Do you know?
