### ISSUE TITLE
rpc call get_content returns empty body and title

### ISSUE THREAD

**Issue by Phistr90** [xeroc/piston#20]
Hi, 

I used the piston lib and did a rpc call get_content against my local steemd node. 
It returns an empty body and title.

If I use the default node this.piston.rocks it returns a body and title.

Any misconfiguration at my steemd node?

**Comment by xeroc** [comment]
Take a look at the documentation about the piston.rocks API that I wrote recently:
http://piston.readthedocs.io/en/develop/public-api.html

**Comment by Phistr90** [comment]
Hi Fabian, I have already tried it. Doesnt work. Anything else?

**Comment by xeroc** [comment]
`this.piston.rocks` does exactly as described in the docs .. it uses the latest git tag (stable release) which happen to be identical with `master`. I don't think this is `piston` related. You may want to read more into how these nodes are set up.
