### ISSUE TITLE
no wheels

### ISSUE THREAD

**Issue by sebwebdesigner** [xeroc/piston#22]
It seems your package has no wheels. I have Visual studio 14.0 but I get "unable-to-find-vcvarsall-bat"
any ideas?
ok i fixed that by adding "common tools" to visual studio and now I get : 
scrypt-1.1.6/lib/scryptenc\scryptenc.h(33): fatal error C1083: Cannot open include file: 'win_stdint.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2

**Comment by xeroc** [comment]
Unfortunately this seems to be an issuer with the scrypt package, and not with piston:
https://bitbucket.org/mhallin/py-scrypt/issues/18/scrypt-is-not-pip-installable-on-windows
