### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by UngratefulFool** [xeroc/piston#23]
I have tried install steem piston both through the manual install and pip3 install steem-piston. When I successfully install it I try to do piston --help through terminal and only get "Command does not exist." Could you elaborate the installation and possibly provide me the prerequisites and possible solutions?
Thank you

**Comment by xeroc** [comment]
The piston binary is installed in ~/.local/bin .. if your `PATH` variable is not properly setup, you won't find it.
You can call piston directly using

    ~/.local/bin/piston --help

**Comment by UngratefulFool** [comment]
What Operating system are you using? I have tried debian, Mac OS X and Windows. I keep getting errors before being able to use it. What am I doing wrong? Are there more obvious steps to doing this that everyone assumes? Are there any dependencies? Thank you for your assistance.
