### ISSUE TITLE
Installation failed twice

### ISSUE THREAD

**Issue by bitcoinmeetups** [xeroc/piston#25]
Installation failed twice

Installation of piston failed twice. Install with pip failed. Manual installation failed. Different error messages.

Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-id1lzx_x/scrypt/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install —record /tmp/pip-sgigdc73-record/install-record.txt —single-version-externally-managed —compile —user failed with error code 1 in /tmp/pip-build-id1lzx_x/scrypt

1.6/lib/crypto/crypto_aesctr.c -o build/temp.linux-x86_64-3.4/scrypt-1.1.6/lib/crypto/crypto_aesctr.o -O2

scrypt-1.1.6/lib/crypto/crypto_aesctr.c:38:25: fatal error: openssl/aes.h: No such file or directory

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by xeroc** [comment]
please install `libssl-dev` to obtain the `aes.h` file

**Comment by bitcoinmeetups** [comment]
I have done that. Now it asks for yaml.c I think. Is that available somewhere?

**Comment by xeroc** [comment]
any you try:

    apt-get install -y git make gcc libssl-dev libgmp-dev python-dev libxml2-dev libxslt1-dev zlib1g-dev libyaml

that hopefully installs all dependencies

**Comment by proctologic** [comment]
install
sudo apt-get install python-yaml python-requests
