### ISSUE TITLE
Posting by command line errors

### ISSUE THREAD

**Issue by MarcGodard** [xeroc/piston#4]
Vim: Warning: Input is not from a terminal
Vim: Error reading input, exiting...
Vim: preserving files...
Vim: Finished.
Empty body! Not posting!

**Comment by MarcGodard** [comment]
```
cat somefile.txt | piston post --author marcgodard --category "test" --title "testing commandline posting" --permlink "something-here"
```

**Comment by xeroc** [comment]
I have `EDITOR=vim` and have noticed that it doesn't work properly with `EDITOR=gvim`. Not sure how that should be done properly so that the editor doesn't actually *detach* ...
Need to look into this ..

**Comment by xeroc** [comment]
"wannabe" fix:
https://github.com/xeroc/piston/commit/f8e30333a5d745a6512ae2bac1f25dd5de083752
