### ISSUE TITLE
not able to get post content?

### ISSUE THREAD

**Issue by sfinder** [xeroc/piston#43]

**Comment by sfinder** [comment]
following statement only return the title of the post not the full content  

import piston
from piston.steem import Steem, Post, MissingKeyError
wif = "5JeSeavcEzk*******************"
steem = Steem(wif=wif)
print(steem.get_content("@corbettreport/the-corbett-report-is-here-here-s-how-i-introduced-steemit-to-my-150-000-youtube-subscribers"))

return:
python3 test_post.py 
<Steem.Post-@corbettreport/the-corbett-report-is-here-here-s-how-i-introduced-steemit-to-my-150-000-youtube-subscribers>

**Comment by sfinder** [comment]
need to add .body.... resloved .... thanks

**Comment by xeroc** [comment]
Use this:

```
from piston.steem import Steem, Post
p = Post(Steem(), "@corbettreport/the-corbett-report-is-here-here-s-how-i-introduced-steemit-to-my-150-000-youtube-subscribers")
p.body
```
