### ISSUE TITLE
Integrating exchange_rate and feed_publish

### ISSUE THREAD

**Issue by aaroncox** [xeroc/piston#45]
Hey @xeroc! I abstracted two classes so that I could use the Steem class to build an application that updates the witness price feed. 

Here are the two classes I've added (which maybe could be one?):

- Exchange_rate
- Feed_publish

Here's the problem, I have no idea how to compile piston from source, test appropriated and actually implement these changes the way they should be. 

Below are the lines of code I added with the relevant information:

https://github.com/aaroncox/steemfeed/blob/2d197e703491d1b0650049ac73b4d7f49433c105/steemfeed.py#L36-L72

I can either work with you via chat and figure this out, or you're free to add them yourself. I'm just opening an issue so I we can track this.

**Comment by xeroc** [comment]
Hi @aaroncox, 
good job on the code so far.
Usually, the operations are part of python-steem ([see here](https://github.com/xeroc/python-steemlib/blob/master/steembase/operations.py#L141))
and piston.steem class merely uses python-steem and combines it all with a private key ([see here](https://github.com/xeroc/piston/blob/master/piston/steem.py#L495-L529))

The `piston` cli command uses the piston.steem class to offer the command line tool ..

This is how you can go forward:

1. Please send a pull request to python-steem (`develop` branch) to add the `Exchange_rate` and `Feed_publish`?
2. Send a pull request for piston (the steem.py) file and add a call like `publish_price_feed`. This requires that you obtain the wif key from the piston wallet .. or that you load `Steem()` with the wif key ([read this](https://github.com/xeroc/piston/blob/develop/piston/steem.py#L272-L285))


Does that answer your questions?

**Comment by aaroncox** [comment]
Yeah, I believe so. Apologies for stopping on this progress, I'm still planning on integrating these changes. One of the things to do on my very long todo list is rewrite the price feed application I'm using and integrate these changes as you've laid out above.
