### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by proctologic** [xeroc/piston#46]
webassets.exceptions.BuildError: [Errno 2] No such file or directory: '/home/witness/.local/lib/python3.5/site-packages/steem_piston-0.3-py3.5.egg/piston/static/libs/sliptree-bootstrap-tokenfield/dist/css/bootstrap-tokenfield.min.css'
127.0.0.1 - - [15/Aug/2016 17:59:05] "GET / HTTP/1.1" 500 -

**Comment by xeroc** [comment]
duplicate #39
