### ISSUE TITLE
Fail to post and vote

### ISSUE THREAD

**Issue by mostar** [xeroc/piston#5]
Install using pip3 on unubtu 14.04
for example whet trying to vote:

piston upvote --voter votername "@lenar79/hacker-shapeshift-confusing-tracks"

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.4/dist-packages/piston/steem.py", line 265, in executeOp
>     self.rpc.broadcast_transaction(tx, api="network_broadcast")
>   File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 373, in method
>     r = self.rpcexec(query)
>   File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 340, in rpcexec
>     raise err
>   File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 336, in rpcexec
>     raise RPCError(ret['error']['message'])
> grapheneapi.graphenewsrpc.RPCError: 10 assert_exception: Assert Exception
> trx.expiration <= now + fc::seconds(STEEMIT_MAX_TIME_UNTIL_EXPIRATION): 
>     {"trx.expiration":"2016-07-16T09:18:54","now":"2016-07-16T07:18:15","max_til_exp":3600}
>     th_a  database.cpp:2740 _apply_transaction
> 
>     {"trx":{"ref_block_num":28384,"ref_block_prefix":3813267277,"expiration":"2016-07-16T09:18:54","operations":[["vote",{"voter":"n...","author":"lenar79","permlink":"hacker-shapeshift-confusing-tracks","weight":10000}]],"extensions":[],"signatures":["1f64...."]}}
>     th_a  database.cpp:2765 _apply_transaction
> 
>     {"trx":{"ref_block_num":28384,"ref_block_prefix":3813267277,"expiration":"2016-07-16T09:18:54","operations":[["vote",{"voter":"n...","author":"lenar79","permlink":"hacker-shapeshift-confusing-tracks","weight":10000}]],"extensions":[],"signatures":["1f64..."]}}
>     th_a  database.cpp:704 push_transaction
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/piston", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.4/dist-packages/piston/__main__.py", line 668, in main
>     voter=args.voter
>   File "/usr/local/lib/python3.4/dist-packages/piston/steem.py", line 450, in vote
>     return self.executeOp(op, wif)
>   File "/usr/local/lib/python3.4/dist-packages/piston/steem.py", line 267, in executeOp
>     raise BroadcastingError
> piston.steem.BroadcastingError

**Comment by xeroc** [comment]
The default API node hasn't been updated to the new fork in time. It is currently reindexing and should be fixed in a few minutes.

**Comment by mostar** [comment]
Thank you it work!
Can my steemd node can be the API node?

**Comment by xeroc** [comment]
Yes it can .. you need to add `rpc-endpoint = 0.0.0.0:<someport>`
then you can use
 
    piston set node ws://<ip>:<sameport>

to override the configuration.

**Comment by mostar** [comment]
When I point to my steemd it fail on:

piston list --sort created --limit 20

```
Traceback (most recent call last):
  File "/usr/local/bin/piston", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/piston/__main__.py", line 733, in main
    start=args.start
  File "/usr/local/lib/python3.4/dist-packages/piston/steem.py", line 715, in get_posts
    for p in func(discussion_query):
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 373, in method
    r = self.rpcexec(query)
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 340, in rpcexec
    raise err
  File "/usr/local/lib/python3.4/dist-packages/grapheneapi/graphenewsrpc.py", line 336, in rpcexec
    raise RPCError(ret['error']['message'])
grapheneapi.graphenewsrpc.RPCError: 10 assert_exception: Assert Exception
_index[space_id].size() > type_id: 
    {"space_id":5,"type_id":3,"index[space_id].size":0}
    th_a  object_database.cpp:57 get_index
```

I can see it comunicate in my steemd output

```
7282ms th_a       database_api.cpp:180          database_api_impl    ] creating database api 1601780752
2967283ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 1, "method": "call", "params": [1, "login", ["", ""]]} 
2967283ms th_a       api.cpp:56                    login                ] user:  password:  
2967283ms th_a       api.cpp:72                    login                ] acc->allowed_apis: ["database_api","network_broadcast_api","tag_api"] 
2967283ms th_a       api.cpp:82                    login                ] known api: database_api
2967283ms th_a       api.cpp:85                    login                ] api_name: network_broadcast_api 
2967283ms th_a       api.cpp:85                    login                ] api_name: tag_api 
2967283ms th_a       application.cpp:379           create_api_by_name   ] unknown api: tag_api
2967283ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 2, "method": "call", "params": [1, "get_api_by_name", ["database_api"]]} 
2967283ms th_a       api.cpp:106                   get_api_by_name      ] found api: database_api
2967283ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 3, "method": "call", "params": [1, "get_api_by_name", ["network_broadcast_api"]]} 
2967284ms th_a       api.cpp:106                   get_api_by_name      ] found api: network_broadcast_api
2967284ms th_a       websocket_api.cpp:88          on_message           ] message: {"jsonrpc": "2.0", "id": 4, "method": "call", "params": [0, "get_discussions_by_created", [{"limit": 20, "tag": null}]]} 
2967324ms th_a       database_api.cpp:185          ~database_api_impl   ] freeing database api 1601780752
```
