### ISSUE TITLE
error: pathspec 'feature/standalone-web' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by l0k1-smirenski** [xeroc/piston#55]
I was just about to dig into this, realising that the back-end side of it could be split off and an interface glue made so it could plug into multiple interface frontends. but the error in the title is what comes up when I try to check out the piston.web. I maybe just am asking, where can I find the piston.web code, so I can generalise its interface glue and port it to other frontends, like gtk3, wxwidgets, and qt.

**Comment by cryptomental** [comment]
@l0k1-smirenski you may want to check 'develop' branch and  https://github.com/cryptomental/docker-steem-piston-web/blob/master/Dockerfile if you have issues to set up the workspace.

**Comment by xeroc** [comment]
@l0k1-smirenski that initial post is outdated. The branch has been merged into the master branch. The corresponding code is in `piston/web.py`
