### ISSUE TITLE
get_blog() no longer works

### ISSUE THREAD

**Issue by Netherdrake** [xeroc/piston#74]
I have been running into this error lately, and its very prevalent, yet intermittent in nature.

Steps to recreate:
```
piston.steem.Steem().get_blog("username")
```

Error:
```
  File "/home/x/anaconda3/lib/python3.5/site-packages/piston/steem.py", line 1019, in get_blog
    user, p   # FIXME, this is a inconsistency in steem backend
KeyError: 'steemsports/steemsports/steemsports-edmonton-oilers-vs-new-york-islanders-mass-sp-distribution-game'
```

![](https://i.gyazo.com/db10b2c732e2902fc503a54d34d930e6.png)

I am on latest `master` of piston stack, and using `this.piston.rocks` and `node.steem.ws`.

**Comment by Netherdrake** [comment]
I have created a temporary workaround for steemtools:
https://github.com/Netherdrake/steemtools/commit/d3febff21ff7862aa9c72b2efac49703e6ee8ac2

**Comment by xeroc** [comment]
So it seems they fixed the inconsistency mentioned in the original sources :D

**Comment by Netherdrake** [comment]
Yes, it was very confusing for a while, since it was intermittent. I suppose that was due to some nodes being 14.2 and some 15.
