### ISSUE TITLE
Add features for market maker bots

### ISSUE THREAD

**Issue by clayop** [xeroc/piston#79]
1. To easily tract existing orders, orderid should be included in `buy` and `sell` as an option. (default is random as like the current setting)
2. `cancel` command is needed. Required parameter is orderid.

**Comment by xeroc** [comment]
This stuff is now in python-steem and no longer in piston:
https://github.com/xeroc/python-steem/commit/b8464a8f1fb50ebee10034001fd999bcfba9883c
https://github.com/xeroc/python-steem/commit/5e620ced3a7206d0ee85bcf0b6597f4b9063827f
