### ISSUE TITLE
Dump Private Keys

### ISSUE THREAD

**Issue by MarcGodard** [xeroc/piston#8]
Is there a way to dump the private keys?

**Comment by xeroc** [comment]
Currently there is no call for that, but I am working on a more robust solution for piston's wallet all-together.
In the meantime you can run this simply thing in python:
```python
from piston.steem import Steem
from piston.wallet import Wallet
wallet = Wallet(Steem())
wallet.ensureOpen()
wallet.keys
```

**Comment by xeroc** [comment]
There is now a 

    piston getkey STM.....

**Comment by MarcGodard** [comment]
Awesome. Thank you. Great library.
