### ISSUE TITLE
piston addkey KEY not working

### ISSUE THREAD

**Issue by MarcGodard** [xeroc/piston#80]
In the new release, if I try to add a key using the piston addkey PRIVEKEY it doens't work, gives an error.

**Comment by pmartynov** [comment]
Hey @MarcGodard , just call `piston addkey` and then insert your key.

**Comment by MarcGodard** [comment]
@pmartynov I use scripts that cannot use that solution.

**Comment by xeroc** [comment]
Thanks for the bug report .. I removed that feature due to security concerns but it was readded with a parameter in this commit: https://github.com/xeroc/piston/commit/b45c5760c05c03d0f085e2a8139c696958dddd19
