### ISSUE TITLE
import error no module named piston

### ISSUE THREAD

**Issue by grey580** [xeroc/piston#84]
I'm attempting to install piston on a mini install of ubuntu.

I've downloaded the dependencies necessary to do the install.

And according to the installation piston installed.

Now when I run my script on the command line I get an error.

python3 bot.py
traceback (most recent call last):
File "bot.py" , line 8, in <module>
from piston.steem import Steem
ImportError: No module named 'piston'

I can only assume that something didn't install correctly in the right place.

Any ideas?

**Comment by grey580** [comment]
well..... 
Now I tried steem.steem
and the bot runs. however i have to comment out Broadcasting error.

cannot import name broadcasting error

**Comment by xeroc** [comment]
Can you give us a full code snippet?

**Comment by grey580** [comment]
Hi xeroc.
I'm attempting to get fyrstikkens oprah bot to run.

https://steemit.com/upvote-bot/@fyrstikken/updated-winfrey-upvote-bot-will-vote-for-everyone-who-post-on-steemit-with-a-2-upvote-except-posts-flagged-by-cheetah-or

`# This Piston/Python-Bot will vote for everyone who post except those flagged by
# @cheetah or @steemcleaners. By Default the Upvote is set at 2%
# Created by: @furion, @contentjunkie, @anyx, @inertia, @fyrstikken
# Make sure you have the latest version of Python and Piston installed
# See Original Post for details and step by step process.
# For help come on http://steemspeak.com or http://steemit.chat

from piston.steem import Steem
from piston.steem import BroadcastingError
import threading
import time
import random
import csv

# my favorite blogs on steemit
top_writers = []

# add my favorites 
my_favorites = []

# Skiplist functionality has not been added yet, this will be your personal blacklist
with open('skiplist.txt', mode='r') as infile:
    reader = csv.reader(infile)
    for rows in reader:
        v = rows[0]
        top_writers.append(v)
# Add your Account, Posting key for voting and/or Active Key for tipping 
my_subscriptions = top_writers + my_favorites
account = ["your-account-name"]
posting_key = ["your-private-posting-key"]
active_key = []
# This is the range (in seconds) in which your bot will cast a vote
vote_delay = random.randrange(1200,1800)
 
upvote_history = []
 
def feed():
# Starting The Bot
    print("Upvote Bot Started - Waiting for New Posts to Upvote!")
    steem = Steem(wif=posting_key[0])
    for comment in steem.stream_comments():
 
        if True: 
# Just making sure we vote for the post and not a comment.
            if comment.depth == 0:
 
# check if we already upvoted this. Sometimes the feed will give duplicates.
                if comment.identifier in upvote_history:
                    continue
 
                print("New post by @%s %s" % (comment.author, url_builder(comment)))
                workerThread = threading.Thread(name=comment.identifier, target=worker, args=(comment,))
                workerThread.start()
 
# Tipping Function send $0.001 in STEEM
def send_a_tip(author):
    steem = Steem(wif=active_key)
    steem.transfer(author, 0.001, "STEEM", memo="Keep Blogging", account=account)
 
 
def url_builder(comment):
    return "https://steemit.com/%s/%s" % (comment.category, comment.identifier)
 
def worker(worker_comment):
     time.sleep(vote_delay)
     try:
       for (k,v) in enumerate(account):
         worker_steem = Steem(wif=posting_key[k])
         upvote_comment = worker_steem.get_content(worker_comment.identifier)
# Checking if Post is flagged for Plagarism & Spam
         names = ['steemcleaners', 'cheetah']
         for avote in upvote_comment['active_votes']:
           if (avote['voter'] in names and avote['percent'] < 0):
            print("====> Upvote Skipped - Post Flagged by Cheetah or Steemcleaners")
            return False
# If the post has not been flagged by Cheetah or Steemcleaners, it will now upvote the post
# with a 2 % upvote 
         upvote_comment.vote(2, v)
# Upvote has now been done and it will now print a message to your screen:
         print("====> Post Upvoted Successfully!")
         upvote_history.append(upvote_comment.identifier)
     except BroadcastingError as e:
       print("Upvoting failed...")
       print("We have probably already upvoted this post before the author edited it.")
       print(str(e))
 
       if upvote_comment.author in my_favorites:
         send_a_tip(upvote_comment.author)
         print("====> Sent $0.001 STEEM to @%s" % upvote_comment.author)
 
 
if __name__ == "__main__":
    while True:
        try:
            feed()
        except (KeyboardInterrupt, SystemExit):
            print("Quitting...")
            break
        except Exception as e:
            traceback.print_exc()
            print("### Exception Occurred: Restarting...")

# If you want to add more complexity to the Bot, feel free to do so and share it with
# The Steemit community on your own Blog.
`

I think I've narrowed it down to it being that this script will not run with the latest version of piston.
Any suggestions?

**Comment by grey580** [comment]
Solved the issue by completely uninstalling steem

and using pip3 install steem==0.3.1

Seems like the latest version of steem has broken almost everyone's scripts.

**Comment by bycz6** [comment]
Hello,

I have the same error.
When I try pip3 install steem==0.3.1

`Collecting steem==0.3.1
  Could not find a version that satisfies the requirement steem==0.3.1 (from versions: 0.17.0, 0.17.1)
No matching distribution found for steem==0.3.1
`

**Comment by xeroc** [comment]
Please see this announcement:
https://steemit.com/chainsquad/@chainsquad/python-steem-rebranding-to-piston-libpiston-cli
