### ISSUE TITLE
Script/vote causing odd exception

### ISSUE THREAD

**Issue by gitbase1** [xeroc/piston#89]
Not sure if something is wrong in my code, but getting this exception on the worker vote:

'  File "/home/ubuntu/.local/lib/python3.5/site-packages/steem-0.4.4-py3.5.egg/steemapi/steemnoderpc.py", line 140, in rpcexec
    raise exceptions.DuplicateTransaction(msg)
steemapi.exceptions.DuplicateTransaction: Duplicate transaction check failed'

then 

' Lost connection to node during wsconnect(): wss://this.piston.rocks (2/-1) Retrying in 2 seconds '

' Segmentation fault (core dumped) '

Usually 1 or 2 votes happen, but then 

the script dies. 
-------

```
import json
import threading
import time
import csv

from steem import Steem
from time import localtime

posting_key = "blahblah"
steem = Steem(wif=posting_key)

def worker(c):
	time.sleep(5)
	c.upvote(weight=1, voter="blahblah")
	print("====> Upvoted")

for c in steem.stream_comments():
    if c["author"]:
        workerThread = threading.Thread(name=c.identifier, target=worker, args=(c,))   
        workerThread.start()
        print("working")
    else:
    	print(c["author"])    

```

**Comment by Netherdrake** [comment]
Why do you need threading here? Voting shouldn't take too long, so it might as well be synchronous.

`c` comes bound with active websocket connection, and that is inherently not thread-safe.

**Comment by gitbase1** [comment]
Thanks @Netherdrake 👍  the reason is because ultimately there will be a delay time on the vote (10 minutes).  If the sleeper takes place in the stream_comments, what happens for other votes that meet the criteria?  won't they not be processed until the sleeper is done?

**Comment by Netherdrake** [comment]
What if you just pass the identifier, and then re-create the post in the thread?

```
def worker(identifier):
	time.sleep(5)
        p = Post(identifier)
	p.upvote(weight=1, voter="blahblah")
	print("====> Upvoted")
```

**Comment by gitbase1** [comment]
Good idea that should solve it, perhaps the object is too large.  Only issue is Post(identifier) causes an exception, because Post is not defined.  Is there a special way to define that method to lookup the Post?

**Comment by Netherdrake** [comment]
ok, Im not sure if this will work, but its worth a try:

Instead of passing post object, just pass identifier to the worker:
```
from steem.post import Post

def worker(identifier):
	time.sleep(5)
        s = Steem()
        p = Post(identifier, s)
	p.upvote(weight=1, voter="blahblah")
	print("====> Upvoted")
```

**Comment by Netherdrake** [comment]
Ok, I've tested, and this seems to work.

```
import threading
import time

from steem import Steem
from steem.post import Post


def worker(identifier, delay=5):
    time.sleep(delay)
    p = Post(identifier, Steem())
    p.upvote(weight=50, voter="barbara2")
    print("====> Upvoted")


steem = Steem()
for c in steem.stream_comments():
    if c["author"]:
        workerThread = threading.Thread(name=c.identifier, target=worker, args=(c.identifier,))
        workerThread.start()
        print("working")
```

You will need to update to latest version of `develop`, because the master version doesn't support websocket instance overloading yet.

```
pip install -U git+https://github.com/xeroc/python-steem@develop
```

**Comment by xeroc** [comment]
I also noticed that Steem() isnt 'thread-safe'. Need to look more into what we need to make it so it works properly within Threads. I bet we would need a separated RPC connection for every Thread.

**Comment by gitbase1** [comment]
@Netherdrake Thanks! works like a charm.
